'use client'

import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'

export default function GrowthPanel({activeChild}){
 const [items,setItems]=useState([]),[form,setForm]=useState({weight_kg:'',height_cm:'',measured_on:new Date().toISOString().slice(0,10)}),[status,setStatus]=useState({loading:false,error:'',success:''})
 const load=async()=>{if(!activeChild){setItems([]);return}setStatus(s=>({...s,loading:true}));const {data,error}=await supabase.from('measurements').select('*').eq('child_id',activeChild.id).order('measured_on',{ascending:false});setItems(data||[]);setStatus({loading:false,error:error?'Não foi possível carregar o histórico.':'',success:''})}
 useEffect(()=>{load()},[activeChild?.id])
 const save=async e=>{e.preventDefault();const {error}=await supabase.from('measurements').upsert({child_id:activeChild.id,measured_on:form.measured_on,weight_kg:Number(form.weight_kg),height_cm:Number(form.height_cm)},{onConflict:'child_id,measured_on'});if(error){setStatus(s=>({...s,error:'Não foi possível salvar a medição.'}));return}setForm({...form,weight_kg:'',height_cm:''});await load();setStatus(s=>({...s,success:'Medição registrada sem gerar interpretação clínica.'}))}
 if(!activeChild)return <div className="useful-empty"><span>CRESCIMENTO</span><h3>Selecione um perfil infantil.</h3><p>O histórico só aparece dentro do perfil escolhido.</p></div>
 return <div className="growth-module"><div className="module-heading"><p className="kicker">CRESCIMENTO E DESENVOLVIMENTO</p><h2>Histórico com contexto, sem metas corporais.</h2><p>Registramos medidas ao longo do tempo. Curvas e interpretações só serão exibidas quando houver referência pediátrica oficial, versionada e integrada.</p></div><div className="growth-summary"><div><small>Perfil</small><b>{activeChild.nickname}</b></div><div><small>Registros</small><b>{items.length}</b></div><div><small>Referência de curva</small><b>{activeChild.sex_for_growth_reference==='female'?'Feminina':activeChild.sex_for_growth_reference==='male'?'Masculina':'Não informada'}</b></div><button className="button outline" onClick={()=>window.print()}>Imprimir relatório</button></div><div className="growth-grid"><form className="module-form" onSubmit={save}><h3>Nova medição</h3><label>Data<input required type="date" max={new Date().toISOString().slice(0,10)} value={form.measured_on} onChange={e=>setForm({...form,measured_on:e.target.value})}/></label><div className="two-fields"><label>Peso registrado (kg)<input required type="number" min="1" max="300" step="0.1" value={form.weight_kg} onChange={e=>setForm({...form,weight_kg:e.target.value})}/></label><label>Altura registrada (cm)<input required type="number" min="20.1" max="250" step="0.1" value={form.height_cm} onChange={e=>setForm({...form,height_cm:e.target.value})}/></label></div>{status.error&&<p className="form-status error">{status.error}</p>}{status.success&&<p className="form-status success">{status.success}</p>}<button className="button primary full">Registrar</button><small className="clinical-note">Nenhum diagnóstico ou “peso ideal” é calculado.</small></form><section className="history-panel"><div><h3>Histórico</h3><span>Mais recente primeiro</span></div>{status.loading?<p>Carregando…</p>:items.length===0?<div className="useful-empty compact">Ainda não há medições. O perfil funciona normalmente sem elas.</div>:<ol>{items.map(item=><li key={item.id}><time>{new Date(item.measured_on+'T12:00:00').toLocaleDateString('pt-BR')}</time><span><b>{item.height_cm} cm</b><small>altura registrada</small></span><span><b>{item.weight_kg} kg</b><small>peso registrado</small></span></li>)}</ol>}</section></div><aside className="report-disclaimer"><b>Relatório informativo</b><p>O histórico pode ser compartilhado pelo responsável com um profissional. Não apresenta diagnóstico, percentil ou recomendação clínica sem dados e referências adequados.</p></aside></div>
}
