'use client'

import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'
import {CATEGORY_LABELS} from '../domain/nutrition/catalog'
import {track} from '../services/analytics'

const empty={food_name:'',quantity:'',unit:'unidade',category:'other',expires_on:''}

export default function PantryPanel({session,onUse}){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState(null),[status,setStatus]=useState({loading:true,error:'',success:''})
 const load=async()=>{setStatus(s=>({...s,loading:true,error:''}));const {data,error}=await supabase.from('pantry_items').select('*').eq('user_id',session.user.id).order('food_name');setItems(data||[]);setStatus({loading:false,error:error?'Não foi possível carregar a despensa.':'',success:''})}
 useEffect(()=>{load()},[session.user.id])
 const visible=useMemo(()=>items.filter(item=>(filter==='all'||item.category===filter)&&item.food_name.toLowerCase().includes(search.toLowerCase())),[items,filter,search])
 const change=(key,value)=>setForm(current=>({...current,[key]:value}))
 const save=async event=>{event.preventDefault();const payload={food_name:form.food_name.trim(),quantity:form.quantity===''?null:Number(form.quantity),unit:form.unit||null,category:form.category,expires_on:form.expires_on||null,user_id:session.user.id};const {error}=editing?await supabase.from('pantry_items').update(payload).eq('id',editing):await supabase.from('pantry_items').insert(payload);if(error){setStatus(s=>({...s,error:'Não foi possível salvar este alimento.'}));return}if(!editing&&items.length===0)track('pantry_created',{userId:session.user.id,metadata:{category:form.category}});setEditing(null);setForm(empty);await load();setStatus(s=>({...s,success:'Despensa atualizada.'}))}
 const edit=item=>{setEditing(item.id);setForm({...item,quantity:item.quantity??'',expires_on:item.expires_on??''})}
 const remove=async id=>{await supabase.from('pantry_items').delete().eq('id',id);load()}
 return <div className="module-stack"><div className="module-heading split"><div><p className="kicker">DESPENSA INTELIGENTE</p><h2>Use primeiro o que já está em casa.</h2><p>Quantidades são opcionais. A lista ajuda no planejamento e não mede o consumo da criança.</p></div><form className="compact-add" onSubmit={save}><input required value={form.food_name} onChange={e=>change('food_name',e.target.value)} placeholder="Adicionar alimento" aria-label="Nome do alimento"/><select value={form.category} onChange={e=>change('category',e.target.value)} aria-label="Categoria">{Object.entries(CATEGORY_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input value={form.quantity} onChange={e=>change('quantity',e.target.value)} type="number" min="0" step="0.1" placeholder="Qtd." aria-label="Quantidade"/><select value={form.unit} onChange={e=>change('unit',e.target.value)} aria-label="Unidade"><option>unidade</option><option>kg</option><option>g</option><option>litro</option><option>pacote</option></select><button className="button primary">{editing?'Atualizar':'Adicionar'}</button>{editing&&<button type="button" className="text-link" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</form></div><div className="list-tools"><label>Buscar na despensa<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Arroz, tomate…"/></label><label>Filtrar<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas as categorias</option>{Object.entries(CATEGORY_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>{status.error&&<p className="form-status error">{status.error}</p>}{status.success&&<p className="form-status success">{status.success}</p>}{status.loading?<div className="useful-empty">Carregando sua despensa…</div>:items.length===0?<div className="useful-empty"><span>DESPENSA VAZIA</span><h3>Comece com três alimentos.</h3><p>Arroz, feijão e tomate já são suficientes para conectar a despensa ao gerador.</p></div>:visible.length===0?<div className="useful-empty">Nenhum alimento corresponde à busca.</div>:<div className="pantry-table" role="table" aria-label="Alimentos da despensa">{visible.map(item=><article role="row" key={item.id}><div className="food-initial" aria-hidden="true">{item.food_name.slice(0,2).toUpperCase()}</div><div><b>{item.food_name}</b><small>{CATEGORY_LABELS[item.category]||'Outro'}{item.expires_on?` · usar até ${new Date(item.expires_on+'T12:00:00').toLocaleDateString('pt-BR')}`:''}</small></div><span>{item.quantity??'—'} {item.quantity!=null?item.unit:''}</span><div className="row-actions"><button onClick={()=>onUse(item.food_name)}>Usar</button><button onClick={()=>edit(item)}>Editar</button><button className="danger-link" onClick={()=>remove(item.id)}>Remover</button></div></article>)}</div>}</div>
}
