'use client'

import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'
import {CATEGORY_LABELS,normalizeFood} from '../domain/nutrition/catalog'
import {track} from '../services/analytics'

const mealLabels={breakfast:'Café da manhã',morning_snack:'Lanche da manhã',lunch:'Almoço',afternoon_snack:'Lanche da tarde',dinner:'Jantar',supper:'Ceia'}

function dateKey(offset=0){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}

export default function PlannerPanel({session,activeChild}){
 const [tab,setTab]=useState('week'),[plans,setPlans]=useState([]),[saved,setSaved]=useState([]),[shopping,setShopping]=useState([]),[habits,setHabits]=useState({water_check:false,movement_check:false,sleep_check:false,family_meal_check:false,new_foods_count:0}),[form,setForm]=useState({planned_for:dateKey(),meal_type:'lunch',meal_id:''}),[newItem,setNewItem]=useState(''),[status,setStatus]=useState({loading:false,error:'',success:''})
 const week=useMemo(()=>Array.from({length:7},(_,index)=>{const value=dateKey(index);return{value,label:new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}}),[])
 const load=async()=>{if(!activeChild){setPlans([]);setSaved([]);setShopping([]);return}setStatus(s=>({...s,loading:true,error:''}));const [{data:p,error:pe},{data:m,error:me},{data:s,error:se},{data:h,error:he}]=await Promise.all([supabase.from('weekly_menu_items').select('*').eq('child_id',activeChild.id).gte('planned_for',week[0].value).lte('planned_for',week[6].value).order('planned_for'),supabase.from('meals').select('id,title,recipe_snapshot,foods').eq('child_id',activeChild.id).eq('saved',true).order('created_at',{ascending:false}).limit(20),supabase.from('shopping_items').select('*').eq('user_id',session.user.id).order('checked').order('created_at'),supabase.from('habit_logs').select('*').eq('child_id',activeChild.id).eq('logged_on',dateKey()).maybeSingle()]);setPlans(p||[]);setSaved(m||[]);setShopping(s||[]);if(h)setHabits(h);setStatus({loading:false,error:(pe||me||se||he)?'Alguns dados não puderam ser carregados.':'',success:''})}
 useEffect(()=>{load()},[activeChild?.id,session.user.id])
 const addPlan=async event=>{event.preventDefault();const meal=saved.find(item=>item.id===form.meal_id);if(!meal){setStatus(s=>({...s,error:'Salve uma refeição antes de adicioná-la ao cardápio.'}));return}const {error}=await supabase.from('weekly_menu_items').upsert({child_id:activeChild.id,planned_for:form.planned_for,meal_type:form.meal_type,title:meal.title,recipe_snapshot:meal.recipe_snapshot||{foods:meal.foods}},{onConflict:'child_id,planned_for,meal_type'});if(error){setStatus(s=>({...s,error:'Não foi possível atualizar o cardápio.'}));return}track('weekly_menu_created',{userId:session.user.id,metadata:{meal_type:form.meal_type}});await load();setStatus(s=>({...s,success:'Cardápio atualizado.'}))}
 const removePlan=async id=>{await supabase.from('weekly_menu_items').delete().eq('id',id);load()}
 const addShopping=async(name,category='other')=>{if(!name.trim())return;await supabase.from('shopping_items').insert({user_id:session.user.id,item_name:name.trim(),category});setNewItem('');load()}
 const generateShopping=async()=>{const [{data:pantry}]=await Promise.all([supabase.from('pantry_items').select('food_name').eq('user_id',session.user.id)]);const atHome=new Set((pantry||[]).map(item=>normalizeFood(item.food_name)));const existing=new Set(shopping.map(item=>normalizeFood(item.item_name)));const foods=plans.flatMap(plan=>plan.recipe_snapshot?.foods||[]).map(item=>typeof item==='string'?{name:item,category:'other'}:item).filter(item=>item?.name&&!atHome.has(normalizeFood(item.name))&&!existing.has(normalizeFood(item.name)));const unique=[...new Map(foods.map(item=>[normalizeFood(item.name),item])).values()];if(unique.length)await supabase.from('shopping_items').insert(unique.map(item=>({user_id:session.user.id,item_name:item.name,category:item.category||'other'})));track('shopping_list_created',{userId:session.user.id,metadata:{item_count:unique.length}});await load();setStatus(s=>({...s,success:unique.length?'Lista criada só com o que não está na despensa.':'Nada novo para comprar: os itens já estão em casa ou na lista.'}))}
 const toggleShopping=async item=>{await supabase.from('shopping_items').update({checked:!item.checked}).eq('id',item.id);load()}
 const removeShopping=async id=>{await supabase.from('shopping_items').delete().eq('id',id);load()}
 const updateHabit=async(key,value)=>{const next={...habits,[key]:value};setHabits(next);await supabase.from('habit_logs').upsert({child_id:activeChild.id,logged_on:dateKey(),water_check:next.water_check,movement_check:next.movement_check,sleep_check:next.sleep_check,family_meal_check:next.family_meal_check,new_foods_count:Number(next.new_foods_count)||0},{onConflict:'child_id,logged_on'})}
 if(!activeChild)return <div className="useful-empty"><span>PLANEJAMENTO</span><h3>Selecione um perfil para planejar.</h3></div>
 return <div className="planner-module"><div className="module-heading"><p className="kicker">PLANEJAMENTO SEMANAL</p><h2>Da refeição salva até a lista de compras.</h2><p>Os módulos compartilham a mesma informação para evitar digitação repetida.</p></div><div className="subtabs" role="tablist"><button role="tab" aria-selected={tab==='week'} onClick={()=>setTab('week')}>Cardápio</button><button role="tab" aria-selected={tab==='shopping'} onClick={()=>setTab('shopping')}>Compras <span>{shopping.filter(item=>!item.checked).length}</span></button><button role="tab" aria-selected={tab==='habits'} onClick={()=>setTab('habits')}>Hábitos</button></div>{status.error&&<p className="form-status error">{status.error}</p>}{status.success&&<p className="form-status success">{status.success}</p>}
 {tab==='week'&&<section className="week-view"><form className="plan-form" onSubmit={addPlan}><label>Dia<select value={form.planned_for} onChange={e=>setForm({...form,planned_for:e.target.value})}>{week.map(day=><option key={day.value} value={day.value}>{day.label}</option>)}</select></label><label>Horário<select value={form.meal_type} onChange={e=>setForm({...form,meal_type:e.target.value})}>{Object.entries(mealLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Refeição salva<select required value={form.meal_id} onChange={e=>setForm({...form,meal_id:e.target.value})}><option value="">Selecione</option>{saved.map(meal=><option value={meal.id} key={meal.id}>{meal.title}</option>)}</select></label><button className="button primary">Adicionar</button></form>{saved.length===0&&<p className="context-note">Gere e salve uma refeição primeiro. Ela ficará disponível aqui.</p>}<div className="week-columns">{week.map(day=><article key={day.value}><header><b>{day.label}</b><small>{day.value===dateKey()?'Hoje':''}</small></header>{plans.filter(plan=>plan.planned_for===day.value).length?plans.filter(plan=>plan.planned_for===day.value).map(plan=><div className="plan-item" key={plan.id}><small>{mealLabels[plan.meal_type]}</small><b>{plan.title}</b><button onClick={()=>removePlan(plan.id)} aria-label={`Remover ${plan.title}`}>×</button></div>):<p>Livre</p>}</article>)}</div><button className="button outline shopping-cta" onClick={generateShopping}>Gerar lista do que falta</button></section>}
 {tab==='shopping'&&<section className="shopping-view"><form onSubmit={e=>{e.preventDefault();addShopping(newItem)}}><input value={newItem} onChange={e=>setNewItem(e.target.value)} placeholder="Adicionar item" aria-label="Novo item de compra"/><button className="button primary">Adicionar</button></form>{shopping.length===0?<div className="useful-empty compact">Sua lista está vazia. Gere a partir do cardápio ou adicione um item.</div>:<div className="shopping-groups">{Object.entries(CATEGORY_LABELS).map(([category,label])=>{const group=shopping.filter(item=>item.category===category);return group.length?<div key={category}><h3>{label}</h3>{group.map(item=><label className={item.checked?'checked':''} key={item.id}><input type="checkbox" checked={item.checked} onChange={()=>toggleShopping(item)}/><span>{item.item_name}</span><button type="button" onClick={()=>removeShopping(item.id)}>Remover</button></label>)}</div>:null})}</div>}</section>}
 {tab==='habits'&&<section className="habits-view"><div className="habit-intro"><h3>Hoje, com {activeChild.nickname}</h3><p>Marque sinais simples da rotina. Não há pontuação, ranking ou punição.</p></div><div className="habit-checks">{[['water_check','Teve água disponível','Hidratação ao longo do dia'],['movement_check','Teve tempo para se movimentar','Brincadeira, caminhada ou atividade preferida'],['sleep_check','A rotina de sono foi cuidada','Horário e ambiente possíveis para a família'],['family_meal_check','Houve uma refeição em família','Conexão sem cobrança para terminar o prato']].map(([key,title,description])=><label key={key}><input type="checkbox" checked={Boolean(habits[key])} onChange={e=>updateHabit(key,e.target.checked)}/><span><b>{title}</b><small>{description}</small></span></label>)}</div><label className="new-food-count">Novos alimentos experimentados nesta semana<input type="number" min="0" max="30" value={habits.new_foods_count||0} onChange={e=>updateHabit('new_foods_count',e.target.value)}/></label></section>}</div>
}
