'use client'

import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {track} from '../services/analytics'

export default function PrivacyPanel({session,onLogout}){
 const [prefs,setPrefs]=useState({email_opt_in:false,whatsapp_opt_in:false,whatsapp_frequency:'off'}),[records,setRecords]=useState([]),[status,setStatus]=useState({loading:true,error:'',success:''})
 const load=async()=>{const [{data:p,error:pe},{data:r,error:re}]=await Promise.all([supabase.from('communication_preferences').select('*').eq('user_id',session.user.id).single(),supabase.from('consent_records').select('*').eq('user_id',session.user.id).order('occurred_at',{ascending:false})]);if(p)setPrefs(p);setRecords(r||[]);setStatus({loading:false,error:(pe||re)?'Não foi possível carregar todas as preferências.':'',success:''})}
 useEffect(()=>{load()},[session.user.id])
 const setConsent=async(purpose,granted)=>{const next={...prefs,[purpose==='whatsapp'? 'whatsapp_opt_in':'email_opt_in']:granted};if(purpose==='whatsapp')next.whatsapp_frequency=granted?'weekly':'off';const {error}=await supabase.from('communication_preferences').update(next).eq('user_id',session.user.id);if(error){setStatus(s=>({...s,error:'Não foi possível salvar sua preferência.'}));return}await supabase.from('consent_records').insert({user_id:session.user.id,purpose:purpose==='whatsapp'?'whatsapp':'email_marketing',status:granted?'granted':'revoked',version:'2026-09-02',source:'account_settings'});setPrefs(next);if(purpose==='whatsapp')track(granted?'whatsapp_opted_in':'whatsapp_opted_out',{userId:session.user.id,metadata:{enabled:granted}});load()}
 const exportData=async()=>{setStatus(s=>({...s,success:'Preparando seu arquivo…'}));const base=await Promise.all([supabase.from('profiles').select('*').eq('id',session.user.id),supabase.from('communication_preferences').select('*').eq('user_id',session.user.id),supabase.from('children').select('*').eq('parent_id',session.user.id),supabase.from('pantry_items').select('*').eq('user_id',session.user.id),supabase.from('shopping_items').select('*').eq('user_id',session.user.id),supabase.from('consent_records').select('*').eq('user_id',session.user.id),supabase.from('deletion_requests').select('*').eq('user_id',session.user.id)]);const childIds=(base[2].data||[]).map(child=>child.id);const byChildren=childIds.length?await Promise.all([supabase.from('measurements').select('*').in('child_id',childIds),supabase.from('meals').select('*').in('child_id',childIds),supabase.from('habit_logs').select('*').in('child_id',childIds),supabase.from('weekly_menu_items').select('*').in('child_id',childIds)]):[{data:[]},{data:[]},{data:[]},{data:[]}];const payload={exported_at:new Date().toISOString(),profile:base[0].data,communication_preferences:base[1].data,children:base[2].data,pantry:base[3].data,shopping:base[4].data,consents:base[5].data,deletion_requests:base[6].data,measurements:byChildren[0].data,meals:byChildren[1].data,habits:byChildren[2].data,weekly_menu:byChildren[3].data};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ai-labs-meus-dados.json';a.click();URL.revokeObjectURL(url);setStatus(s=>({...s,success:'Arquivo exportado para seu dispositivo.'}))}
 const requestDeletion=async()=>{const {error}=await supabase.from('deletion_requests').insert({user_id:session.user.id,scope:'account',status:'requested'});setStatus(s=>({...s,error:error?'Não foi possível registrar o pedido.':'',success:error?'':'Pedido de exclusão registrado. A conta será revisada pelo processo seguro de exclusão.'}))}
 return <div className="privacy-module"><div className="module-heading"><p className="kicker">PRIVACIDADE E CONTROLE</p><h2>Uma escolha para cada finalidade.</h2><p>Usar o produto não obriga você a receber comunicações. Alterações ficam registradas para auditoria.</p></div>{status.error&&<p className="form-status error">{status.error}</p>}{status.success&&<p className="form-status success">{status.success}</p>}<section className="preference-list"><article><div><h3>E-mail com ideias e novidades</h3><p>Conteúdo opcional. Não inclui dados infantis sensíveis.</p></div><button role="switch" aria-checked={prefs.email_opt_in} className={`switch ${prefs.email_opt_in?'on':''}`} onClick={()=>setConsent('email',!prefs.email_opt_in)}><i/><span>{prefs.email_opt_in?'Ativado':'Desativado'}</span></button></article><article><div><h3>Lembretes pelo WhatsApp</h3><p>Planejamento, aproveitamento de alimentos e lista de compras.</p></div><button role="switch" aria-checked={prefs.whatsapp_opt_in} className={`switch ${prefs.whatsapp_opt_in?'on':''}`} onClick={()=>setConsent('whatsapp',!prefs.whatsapp_opt_in)}><i/><span>{prefs.whatsapp_opt_in?'Ativado':'Desativado'}</span></button></article></section><section className="data-actions"><article><h3>Baixar meus dados</h3><p>Gera um arquivo com dados da conta, perfis, despensa, compras e consentimentos.</p><button className="button outline" onClick={exportData}>Exportar dados</button></article><article><h3>Solicitar exclusão</h3><p>Registra uma solicitação auditável. Nenhum dado é apagado sem confirmar a identidade e o escopo.</p><button className="button danger" onClick={requestDeletion}>Solicitar exclusão da conta</button></article></section><section className="consent-history"><div><h3>Histórico de consentimentos</h3><span>{records.length} registro{records.length===1?'':'s'}</span></div>{records.length===0?<p>Nenhuma alteração opcional registrada.</p>:<ol>{records.slice(0,8).map(record=><li key={record.id}><span><b>{record.purpose.replace('_',' ')}</b><small>versão {record.version} · {record.source}</small></span><em className={record.status}>{record.status==='granted'?'Autorizado':'Revogado'}</em><time>{new Date(record.occurred_at).toLocaleDateString('pt-BR')}</time></li>)}</ol>}</section><button className="text-link" onClick={onLogout}>Sair de todos os dados desta sessão</button></div>
}
